apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-qyaoyqjd
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-qyaoyqjd:bc695c77f6c3081b6a222ba7871e17a03faec74c@sha256:1c40521ff81b1bff7c5cddfaf69a7d187a6b78fd2403caaca18b9a1735275d0d
          name: container-image
